name: Docker Build

on:
  push:
    branches:
      - main
      - cicd
      - ecs-migration
      - security-docker-ci
  pull_request:
    branches:
      - main
      - cicd
      - ecs-migration

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t liftlog:test .
